// ✅ Elite Neighbor Map for Smart Suggestions
export const NEIGHBOR_MAP = {
    "Nashik": ["Ahilyanagar", "Dhule", "Jalgaon", "Palghar", "Thane"],
    "Pune": ["Ahilyanagar", "Raigad", "Satara", "Solapur", "Thane"],
    "Mumbai City": ["Mumbai Suburban", "Thane"],
    "Mumbai Suburban": ["Mumbai City", "Thane", "Palghar"],
    "Thane": ["Mumbai Suburban", "Palghar", "Pune", "Ahilyanagar", "Nashik", "Raigad"],
    "Ahilyanagar": ["Nashik", "Pune", "Thane", "Beed", "Dharashiv", "Solapur", "Chhatrapati Sambhajinagar"],
    "Chhatrapati Sambhajinagar": ["Jalgaon", "Nashik", "Ahilyanagar", "Beed", "Jalna"],
    "Nagpur": ["Wardha", "Bhandara", "Chandrapur", "Amravati"],
    "Amravati": ["Nagpur", "Wardha", "Yavatmal", "Washim", "Akola", "Buldhana"],
    "Kolhapur": ["Sangli", "Ratnagiri", "Sindhudurg"],
    "Satara": ["Pune", "Raigad", "Ratnagiri", "Sangli", "Solapur"],
    "Solapur": ["Ahilyanagar", "Pune", "Satara", "Sangli", "Dharashiv"],
    "Sangli": ["Kolhapur", "Satara", "Solapur", "Ratnagiri"],
    "Ratnagiri": ["Raigad", "Satara", "Sangli", "Kolhapur", "Sindhudurg"],
    "Sindhudurg": ["Ratnagiri", "Kolhapur"],
    "Raigad": ["Mumbai Suburban", "Thane", "Pune", "Satara", "Ratnagiri"],
    "Jalgaon": ["Dhule", "Nashik", "Buldhana", "Chhatrapati Sambhajinagar"],
    "Dhule": ["Nandurbar", "Nashik", "Jalgaon"],
    "Nandurbar": ["Dhule"],
    "Jalna": ["Chhatrapati Sambhajinagar", "Beed", "Parbhani", "Buldhana"],
    "Beed": ["Ahilyanagar", "Chhatrapati Sambhajinagar", "Jalna", "Parbhani", "Latur", "Dharashiv"],
    "Latur": ["Beed", "Parbhani", "Nanded", "Dharashiv"],
    "Dharashiv": ["Ahilyanagar", "Solapur", "Beed", "Latur"],
    "Nanded": ["Latur", "Parbhani", "Hingoli", "Yavatmal"],
    "Parbhani": ["Jalna", "Beed", "Latur", "Nanded", "Hingoli", "Buldhana"],
    "Hingoli": ["Washim", "Parbhani", "Nanded", "Yavatmal"],
    "Buldhana": ["Jalgaon", "Akola", "Washim", "Parbhani", "Jalna", "Amravati"],
    "Akola": ["Amravati", "Buldhana", "Washim"],
    "Washim": ["Akola", "Amravati", "Yavatmal", "Hingoli", "Buldhana"],
    "Yavatmal": ["Amravati", "Wardha", "Chandrapur", "Nanded", "Hingoli", "Washim"],
    "Wardha": ["Nagpur", "Amravati", "Yavatmal", "Chandrapur"],
    "Chandrapur": ["Nagpur", "Wardha", "Yavatmal", "Gadchiroli", "Bhandara"],
    "Gadchiroli": ["Chandrapur", "Gondia", "Bhandara"],
    "Bhandara": ["Nagpur", "Gondia", "Chandrapur", "Gadchiroli"],
    "Gondia": ["Bhandara", "Gadchiroli"]
};
