"use client";
import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Sidebar
    dashboard: "Dashboard",
    booking_center: "Booking Center",
    yajman_management: "Yajman Management",
    guruji_management: "Guruji Management",
    pooja_master: "Pooja Master",
    finance_hub: "Finance Hub",
    communication: "Communication",
    operations: "Operations Brain",
    legal: "Legal & Info",
    support_tickets: "Support Tickets",
    reports: "Reports & Analytics",
    super_settings: "Super Settings",
    logout: "Logout",
    trust_name: "Dindori Pranit Yadnyiki",

    // Common UI
    search: "Search...",
    loading: "Loading...",
    no_data: "No records found",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    status: "Status",
    date: "Date",
    actions: "Actions",
    export_csv: "Export CSV",
    today: "Today",
    all_districts: "All Districts",
    all_status: "All Status",
    all_categories: "All Categories",
    success: "Success",
    error: "Error",
    update: "Update",
    amount: "Amount",
    verified: "Verified",
    pending: "Pending",
    active: "Active",
    blocked: "Blocked",
    approved: "Approved",
    rejected: "Rejected",

    // Dashboard
    platform_overview: "Platform Performance Overview",
    bookings: "Bookings",
    total_members: "Total Members",
    yajman: "Yajmans",
    guruji: "Guruji",
    total_revenue: "Total Revenue",
    revenue_trend: "Revenue Trend",
    system_health: "System Health",
    database: "Database",
    auth_service: "Auth Service",
    cloud_functions: "Cloud Functions",
    synced: "Synced",
    live: "Live",
    operational: "Operational",

    // Bookings
    active_bookings: "Active Bookings",
    service_requests: "Service Requests",
    booking_details: "Booking Details",
    yajman_info: "Yajman Information",
    location: "Location Details",
    total_amount: "Total Amount",
    mark_completed: "Mark Completed",
    cancel_booking: "Cancel Booking",
    assigned: "Assigned",
    completed: "Completed",
    cancelled: "Cancelled",
    monitor_services: "Monitor and manage service orders",
    
    // Requests Page
    reschedule_cancel_desc: "Manage rescheduling and cancellations",
    total_requests: "Total Requests",
    sync_requests: "Synchronizing Requests...",
    no_requests: "No matching requests found",
    request: "Request",
    new_requested_schedule: "New Requested Schedule",
    customer_reason: "Customer Reason",
    approve_change: "Approve Change",
    resolved_on: "Resolved on",

    // Availability Center
    availability_center: "Availability Center",
    availability_desc: "Real-time schedule monitoring for service providers",
    check_date: "Check Date:",
    search_placeholder_availability: "Search by name or district...",
    checking_rosters: "Checking Rosters...",
    no_gurujis_found: "No Gurujis found for this search/date",
    occupied: "Occupied for service",
    open_for_bookings: "Open for Bookings",
    booked: "Booked",
    available: "Available",

    // Guruji
    manage_guruji_network: "Manage network of service providers",
    global_availability: "Global Availability",
    guruji_profile: "Guruji Profile",
    guruji_details: "Guruji Details",
    approve: "Approve",
    reject: "Reject",
    rejection_reason: "Reason for rejection",
    status_updated: "Status updated successfully",
    error_kyc: "Could not load KYC details",
    guruji_profile_id: "Guruji Profile ID",
    basic_info: "Basic Information",
    update_professional_profile: "Update Professional Profile",
    kyc_docs: "KYC Verification Documents",
    fetching_secure_data: "Fetching Secure Data...",
    verified_doc: "Verified Document",
    no_kyc_docs: "No KYC documents uploaded yet",
    warning_approve: "Warning: Approving a profile makes the Guruji visible to all Yajmans in the app.",
    approve_profile: "Approve Profile",
    reject_notify: "Reject & Notify",
    unblock_guruji: "Unblock Guruji",
    block_guruji: "Block Guruji Account",

    // Users
    manage_devotees: "Manage all registered devotees",
    user_profile: "User Profile",
    unblock: "Unblock",
    block: "Block",
    mobile: "Mobile Number",
    contact_details: "Contact Details",
    activity: "Activity",
    devotee: "Devotee",
    unnamed_user: "Unnamed User",
    syncing: "Synchronizing...",
    no_users_match: "No users match your filters",
    edit_info: "Edit Information",
    update_profile: "Update Profile",
    unblock_account: "Unblock Account",
    block_account: "Block Account",
    recent_activity: "Recent Activity",

    // Pooja Master
    add_new_pooja: "Add New Pooja",
    manage_catalog: "Manage service catalog and pricing",
    name: "Name",
    price: "Price",
    description: "Description",
    category: "Category",
    image_size_error: "Image size should be less than 2MB",
    upload_failed: "Image upload failed",
    save_failed: "Failed to save details",
    name_marathi: "Name (Marathi)",
    name_english: "Name (English)",
    base_price: "Base Price (₹)",
    trust_share_pct: "Trust Share (%)",
    example_calc_pooja: "Example: On ₹1,000 payment, Trust gets",
    and_guruji_gets_pooja: "and Guruji gets",
    service_status: "Service Status",
    create_pooja_profile: "Create Pooja Profile",
    update_pooja_catalog: "Update Pooja Catalog",

    // Finance Hub
    payouts: "Payouts",
    receipts: "Receipts",
    transactions: "Transactions",
    total_collected: "Total Collected",
    pending_dues: "Pending Dues",
    volume: "Volume",
    mark_paid: "Mark Paid",
    manage_revenue: "Manage transactions and platform revenue",
    total_earnings: "Total Earnings",
    settled: "Settled",
    awaiting: "Awaiting",
    mark_settled: "Mark Settled",
    paid: "Paid",
    manage_settlements: "Manage settlements and earnings",
    earning: "Earning",

    // Communication
    feedbacks: "Feedbacks",
    notifications: "Notifications",
    create_broadcast: "Create Broadcast",
    target_audience: "Target Audience",
    all_audience: "All (Yajman & Guruji)",
    only_yajman: "Only Yajmans",
    only_guruji: "Only Gurujis",
    title: "Title",
    title_placeholder: "Notification title...",
    message_content: "Message Content",
    message_placeholder: "Type message...",
    broadcast_now: "Broadcast Now",
    broadcast_desc: "Broadcast announcements to app users",
    notification_tips: "Notification Tips",
    tip_1: "Keep messages short (under 150 chars).",
    tip_2: "Use for urgent temple alerts.",
    tip_3: "Double check before broadcasting.",
    success_broadcast: "Notification broadcasted successfully!",

    // Settings
    global_config: "Global System Configuration",
    save_settings: "Save Settings",
    trust_commission: "Trust Commission (%)",
    trust_share: "Trust Share (%)",
    guruji_share: "Guruji Share (%)",
    maintenance_mode: "Maintenance Mode",
    app_status: "App Online/Offline Status",
    app_version: "App Version",
    support_contact: "Support Contact Details",
    whatsapp: "WhatsApp Number",
    landline: "Landline Number",
    email: "Support Email",
    api_credentials: "API Credentials",
    razorpay_key: "Razorpay Key ID",
    onesignal_id: "OneSignal App ID",
    success_save: "Settings saved successfully!",
    example_calc: "Example: On ₹1,000 payment, Trust gets",
    and_guruji_gets: "and Guruji gets",
    general: "General",
    roles: "Roles",
    audit: "Audit",
    backup: "Backup",

    // Admin Gate & Security
    access_denied: "Access Denied",
    no_admin_privilege: "Your account does not have administrator privileges.",
    debug_info: "Debug Information",
    role_found: "Role Found",
    back_to_login: "Back to Login",

    // Login
    login_title: "Admin Login",
    reset_access: "Reset Access",
    secure_login: "Secure Login",
    email_placeholder: "Admin Email",
    password_placeholder: "Password",
    forgot_password: "Forgot Password?",
    verify_continue: "Verify & Continue",
    verification_required: "Verification Required",
    enter_otp: "Enter 6-digit OTP"
  },
  mr: {
    // Sidebar
    dashboard: "डॅशबोर्ड",
    booking_center: "बुकिंग केंद्र",
    yajman_management: "यजमान व्यवस्थापन",
    guruji_management: "गुरुजी व्यवस्थापन",
    pooja_master: "पूजा मास्टर",
    finance_hub: "आर्थिक केंद्र",
    communication: "संवाद",
    operations: "ऑपरेशन्स ब्रेन",
    legal: "कायदेशीर आणि माहिती",
    support_tickets: "मदत केंद्र",
    reports: "अहवाल आणि विश्लेषण",
    super_settings: "सुपर सेटिंग्ज",
    logout: "लॉगआउट करा",
    trust_name: "दिंडोरी प्रणित याज्ञिकी",

    // Common UI
    search: "शोधा...",
    loading: "लोड होत आहे...",
    no_data: "माहिती उपलब्ध नाही",
    save: "सेव्ह करा",
    cancel: "रद्द करा",
    delete: "हटवा",
    edit: "संपादन",
    status: "स्थिती",
    date: "तारीख",
    actions: "कृती",
    export_csv: "CSV एक्सपोर्ट",
    today: "आज",
    all_districts: "सर्व जिल्हे",
    all_status: "सर्व स्थिती",
    all_categories: "सर्व श्रेणी",
    success: "यशस्वी",
    error: "त्रुटी",
    update: "अपडेट करा",
    amount: "रक्कम",
    verified: "व्हेरिफाईड",
    pending: "प्रलंबित",
    active: "सक्रिय",
    blocked: "ब्लॉक केलेले",
    approved: "मंजूर",
    rejected: "नाकारलेले",

    // Dashboard
    platform_overview: "प्लॅटफॉर्म कामगिरी आढावा",
    bookings: "बुकिंग्ज",
    total_members: "एकूण सदस्य",
    yajman: "यजमान",
    guruji: "गुरुजी",
    total_revenue: "एकूण उत्पन्न",
    revenue_trend: "उत्पन्न कल",
    system_health: "प्रणाली आरोग्य",
    database: "डेटाबेस",
    auth_service: "ऑथ सेवा",
    cloud_functions: "क्लाउड फंक्शन",
    synced: "सिंक झाले",
    live: "लाईव्ह",
    operational: "सुरू",

    // Bookings
    active_bookings: "सक्रिय बुकिंग्ज",
    service_requests: "सेवा विनंत्या",
    booking_details: "बुकिंग तपशील",
    yajman_info: "यजमान माहिती",
    location: "ठिकाण तपशील",
    total_amount: "एकूण रक्कम",
    mark_completed: "पूर्ण झाले",
    cancel_booking: "बुकिंग रद्द करा",
    assigned: "सोपविले",
    completed: "पूर्ण",
    cancelled: "रद्द",
    monitor_services: "सेवा ऑर्डर्सचे निरीक्षण आणि व्यवस्थापन करा",
    
    // Requests Page
    reschedule_cancel_desc: "पुनर्निर्धारण आणि रद्दीकरण व्यवस्थापित करा",
    total_requests: "एकूण विनंत्या",
    sync_requests: "विनंत्या सिंक होत आहेत...",
    no_requests: "कोणतीही विनंती सापडली नाही",
    request: "विनंती",
    new_requested_schedule: "नवीन विनंती केलेले वेळापत्रक",
    customer_reason: "ग्राहकाचे कारण",
    approve_change: "बदल मंजूर करा",
    resolved_on: "रोजी पूर्ण झाले",

    // Availability Center
    availability_center: "उपलब्धता केंद्र",
    availability_desc: "सेवा देणाऱ्यांच्या वेळापत्रकाचे रिअल-टाइम निरीक्षण",
    check_date: "तारीख निवडा:",
    search_placeholder_availability: "नाव किंवा जिल्ह्यानुसार शोधा...",
    checking_rosters: "रोस्टर तपासत आहे...",
    no_gurujis_found: "या तारखेसाठी कोणतेही गुरुजी सापडले नाहीत",
    occupied: "सेवेसाठी व्यस्त",
    open_for_bookings: "बुकिंगसाठी उपलब्ध",
    booked: "बुक केलेले",
    available: "उपलब्ध",

    // Guruji
    manage_guruji_network: "सेवा देणाऱ्यांचे नेटवर्क व्यवस्थापित करा",
    global_availability: "जागतिक उपलब्धता",
    guruji_profile: "गुरुजी प्रोफाइल",
    guruji_details: "गुरुजी तपशील",
    approve: "मंजूर करा",
    reject: "नाकारा",
    rejection_reason: "नाकारण्याचे कारण",
    status_updated: "स्थिती यशस्वीरित्या बदलली",
    error_kyc: "KYC तपशील लोड होऊ शकले नाहीत",
    guruji_profile_id: "गुरुजी प्रोफाइल ID",
    basic_info: "मूलभूत माहिती",
    update_professional_profile: "व्यावसायिक प्रोफाइल अपडेट करा",
    kyc_docs: "KYC पडताळणी कागदपत्रे",
    fetching_secure_data: "सुरक्षित डेटा मिळवत आहे...",
    verified_doc: "व्हेरिफाईड दस्तऐवज",
    no_kyc_docs: "अद्याप कोणतेही KYC दस्तऐवज अपलोड केलेले नाहीत",
    warning_approve: "चेतावणी: प्रोफाइल मंजूर केल्यास गुरुजी ॲपमधील सर्व यजमानांना दिसतील.",
    approve_profile: "प्रोफाइल मंजूर करा",
    reject_notify: "नाकारा आणि सूचित करा",
    unblock_guruji: "गुरुजी अनब्लॉक करा",
    block_guruji: "गुरुजी खाते ब्लॉक करा",

    // Users
    manage_devotees: "सर्व नोंदणीकृत भाविकांचे व्यवस्थापन करा",
    user_profile: "युजर प्रोफाइल",
    unblock: "अनब्लॉक",
    block: "ब्लॉक",
    mobile: "मोबाईल नंबर",
    contact_details: "संपर्क तपशील",
    activity: "कार्यकलाप",
    devotee: "भाविक",
    unnamed_user: "निनावी वापरकर्ता",
    syncing: "सिंक होत आहे...",
    no_users_match: "तुमच्या फिल्टरशी जुळणारे कोणतेही वापरकर्ते नाहीत",
    edit_info: "माहिती संपादित करा",
    update_profile: "प्रोफाइल अपडेट करा",
    unblock_account: "खाते अनब्लॉक करा",
    block_account: "खाते ब्लॉक करा",
    recent_activity: "अलीकडील क्रियाकलाप",

    // Pooja Master
    add_new_pooja: "नवीन पूजा जोडा",
    manage_catalog: "सेवा कॅटलॉग आणि किंमती व्यवस्थापित करा",
    name: "नाव",
    price: "किंमत",
    description: "वर्णन",
    category: "श्रेणी",
    image_size_error: "फोटोची साईज २MB पेक्षा कमी असावी",
    upload_failed: "फोटो अपलोड अयशस्वी",
    save_failed: "माहिती सेव्ह करण्यात त्रुटी आली",
    name_marathi: "नाव (मराठी)",
    name_english: "नाव (इंग्रजी)",
    base_price: "मूळ किंमत (₹)",
    trust_share_pct: "ट्रस्ट हिस्सा (%)",
    example_calc_pooja: "उदा: १००० रुपयांच्या पेमेंटवर ट्रस्टला मिळतील",
    and_guruji_gets_pooja: "आणि गुरुजींना मिळतील",
    service_status: "सेवा स्थिती",
    create_pooja_profile: "पूजा प्रोफाइल तयार करा",
    update_pooja_catalog: "पूजा कॅटलॉग अपडेट करा",

    // Finance Hub
    payouts: "पेआउट्स",
    receipts: "पावत्या",
    transactions: "व्यवहार",
    total_collected: "एकूण जमा",
    pending_dues: "बाकी रक्कम",
    volume: "एकूण व्यवहार",
    mark_paid: "पेमेंट झाले",
    manage_revenue: "व्यवहार आणि प्लॅटफॉर्म उत्पन्नाचे व्यवस्थापन",
    total_earnings: "एकूण कमाई",
    settled: "सेटल केलेले",
    awaiting: "प्रतीक्षेत",
    mark_settled: "सेटलमेंट पूर्ण करा",
    paid: "पेड",
    manage_settlements: "सेटलमेंट आणि कमाईचे व्यवस्थापन",
    earning: "कमाई",

    // Communication
    feedbacks: "फीडबॅक",
    notifications: "सूचना",
    create_broadcast: "ब्रॉडकास्ट तयार करा",
    target_audience: "लक्ष्य गट",
    all_audience: "सर्व (यजमान आणि गुरुजी)",
    only_yajman: "फक्त यजमान",
    only_guruji: "फक्त गुरुजी",
    title: "शीर्षक",
    title_placeholder: "सूचनेचे शीर्षक...",
    message_content: "संदेश मजकूर",
    message_placeholder: "संदेश टाईप करा...",
    broadcast_now: "आता पाठवा",
    broadcast_desc: "ॲप वापरकर्त्यांना सूचना पाठवा",
    notification_tips: "महत्वाच्या टिप्स",
    tip_1: "संदेश लहान ठेवा (१५० अक्षरांपेक्षा कमी).",
    tip_2: "तातडीच्या सूचनांसाठी वापरा.",
    tip_3: "पाठवण्यापूर्वी पुन्हा तपासा.",
    success_broadcast: "सूचना यशस्वीरित्या पाठवली गेली!",

    // Settings
    global_config: "जागतिक प्रणाली कॉन्फिगरेशन",
    save_settings: "सेटिंग्ज सेव्ह करा",
    trust_commission: "ट्रस्ट कमिशन (%)",
    trust_share: "ट्रस्ट हिस्सा (%)",
    guruji_share: "गुरुजी हिस्सा (%)",
    maintenance_mode: "मेंटेनन्स मोड",
    app_status: "ॲप चालू/बंद स्थिती",
    app_version: "ॲप व्हर्जन",
    support_contact: "संपर्क तपशील",
    whatsapp: "व्हॉट्सॲप नंबर",
    landline: "लँडलाईन नंबर",
    email: "सपोर्ट ईमेल",
    api_credentials: "API क्रेडेंशियल्स",
    razorpay_key: "रेझरपे की ID",
    onesignal_id: "वनसिग्नल ॲप ID",
    success_save: "सेटिंग्ज यशस्वीरित्या सेव्ह झाल्या!",
    example_calc: "उदा: १००० रुपयांच्या पेमेंटवर ट्रस्टला मिळतील",
    and_guruji_gets: "आणि गुरुजींना मिळतील",
    general: "सामान्य",
    roles: "भूमिका",
    audit: "ऑडिट",
    backup: "बॅकअप",

    // Admin Gate & Security
    access_denied: "प्रवेश नाकारला",
    no_admin_privilege: "तुमच्या खात्याला ॲडमिनिस्ट्रेटरचे अधिकार नाहीत.",
    debug_info: "डीबग माहिती",
    role_found: "भूमिका सापडली",
    back_to_login: "लॉगिनवर जा",

    // Login
    login_title: "ॲडमिन लॉगिन",
    reset_access: "प्रवेश रीसेट करा",
    secure_login: "सुरक्षित लॉगिन",
    email_placeholder: "ॲडमिन ईमेल",
    password_placeholder: "पासवर्ड",
    forgot_password: "पासवर्ड विसरलात?",
    verify_continue: "पडताळणी करा आणि पुढे जा",
    verification_required: "पडताळणी आवश्यक",
    enter_otp: "६-अंकी OTP टाका"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("mr");

  useEffect(() => {
    const savedLang = localStorage.getItem("admin_lang");
    if (savedLang === "en" || savedLang === "mr") {
        setLang(savedLang);
    } else {
        setLang("mr");
        localStorage.setItem("admin_lang", "mr");
    }
  }, []);

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem("admin_lang", l);
  };

  const t = (key) => {
    if (!translations[lang]) return key;
    return translations[lang][key] || translations["en"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
